#pragma config(Sensor, in1,    potL,           sensorPotentiometer)
#pragma config(Sensor, in2,    potR,           sensorPotentiometer)
#pragma config(Motor,  port2,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           sisL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           sisR,          tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "practice/PID Practice003.c";

task main()
{

	pid();

}
