#pragma config(Sensor, in1,    potentiometerArm, sensorPotentiometer)
#pragma config(Sensor, in3,    potentiometerGrab, sensorPotentiometer)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           grabMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           armMotorL,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           armMotorR,     tmotorNone, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void resetArm(){
	if(SensorValue(potentiometerArm) >= 5){
		motor[armMotorL]= -100;
		motor[armMotorR]= -100;
		waitUntil(SensorValue(potentiometerArm) < 5);
		stopMotor(armMotorL);
		stopMotor(armMotorR);
	}else{
		stopMotor(armMotorL);
		stopMotor(armMotorR);
	}
}

void resetGrab(){
	if(SensorValue(potentiometerGrab) <= 3000){//10
		motor[grabMotor]= 100; // move the motor at a speed of 100
		waitUntil(SensorValue(potentiometerGrab) > 3000); // if the potentiometer is bigger than 2000
		stopMotor(grabMotor);// Stop the motor
	}else{
		stopMotor(grabMotor);
	}
}

void grabing(int speed){
		motor[grabMotor]= -speed
		waitUntil(SensorValue(potentiometerGrab) < 20);
		stopMotor(grabMotor);
}

void droping(int speed){
		motor[grabMotor]= speed;
		waitUntil(SensorValue(potentiometerGrab) > 3000);
		stopMotor(grabMotor);
}

void lifting(int speed){
		motor[armMotorL]= speed;
		motor[armMotorR]= speed;
		waitUntil(SensorValue(potentiometerArm) >= 3000);
		stopMotor(armMotorL);
		stopMotor(armMotorR);
}

void move(int speed) {
		motor[leftMotor] = speed;
		motor[rightMotor] = speed;
}

void turnLeft(int speed){
	motor[leftMotor]= speed;
	motor[rightMotor]= -speed;
}

task main()
{
resetArm();
resetGrab();

//Move Stright to the cube
move(127); // at the maximume speed
wait1Msec(3000) // for 2 seconds

grabing(127); // Starts to grab
move(127); // go stright
wait1Msec(3000); // for 2 seconds

lifting(127); // Move the arm up
droping(127); // release it

turnLeft(100); // turn left
wait1Msec(500); // for 300 micosecond
move(127); // Move forward at a maximume speed
wait1Msec(5000); // for 5 second

turnLeft(100); // Turn left back at a speed of 100
move(127); // Turn left back at a miximume speed
wait1Msec(500); // for 300 microsecond

}
