#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in6,    rightGrab,      sensorPotentiometer)
#pragma config(Sensor, in7,    leftGrab,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  shaft,          sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  left,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  right,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port2,           Tright,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Bright,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightGrab,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftGrab,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Bleft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Tleft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int x;
void liftMove(){
	nMotorEncoder[leftMotor] = 0;
	nMotorEncoder[rightMotor] = 0;

  while(nMotorEncoder[leftMotor] < 1200){

    motor[rightMotor] = 90;
    motor[leftMotor] = 90;

    if(SensorValue[shaft] < 80){
		  motor[Tright] = 60;
			motor[Bright] = 60;
			motor[Bleft] = 60;
			motor[Tleft] = 60;
		}else {
			motor[Tright] = 15;
			motor[Bright] = 15;
			motor[Bleft] = 15;
			motor[Tleft] = 15;
		}
	}
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}


void turnRight(){
	nMotorEncoder[rightMotor] = 0;
	nMotorEncoder[leftMotor] = 0;

	while(abs(nMotorEncoder[rightMotor]) < 300){
		x = nMotorEncoder[rightMotor];
		motor[leftMotor] = 35;
		motor[rightMotor]= -35;
		if(SensorValue[shaft] > 75){
			motor[Tright] = 15;
			motor[Bright] = 15;
			motor[Bleft] = 15;
			motor[Tleft] = 15;
		}else{
			motor[Tright] = 0;
			motor[Bright] = 0;
			motor[Bleft] = 0;
			motor[Tleft] = 0;
		}
	}
}


task main()
{
	SensorValue[shaft] = 0;
  liftMove();
  turnRight();
}
