#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  armEncoder,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  grabEncoder,    sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           TrightMotor,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BrightMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           grabMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BleftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           TleftMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void	dropTheGrab(){
		motor[leftMotor]= 90;
		motor[rightMotor]= 90;

		wait1Msec(400);

		motor[leftMotor]= 127;
		motor[rightMotor]= 127;

		wait1Msec(300);
}


		void openGrab(int speed){
			motor[grabMotor]= speed;
			wait1Msec(2500);	//Open for two seconds
		}

		void grabing(int speed, int val){
			SensorValue(grabEncoder) = 0;
			motor[grabMotor]= speed * -1;
			waitUntil(SensorValue(grabEncoder) >= val);
			motor[grabMotor]= 0;
		}

		void droping(int speed, int val){
			SensorValue(grabEncoder) = 0;
			motor[grabMotor]= speed;
			waitUntil(SensorValue(grabEncoder) >= val);
			motor[grabMotor]= 0;
		}

		void lift(int speed, int val){

			SensorValue(armEncoder)= 0;

			motor[TrightMotor]= speed;
			motor[BrightMotor]= speed;
			motor[BleftMotor]= speed;
			motor[TleftMotor]= speed;

			waitUntil(SensorValue(armEncoder) >= val);

			motor[TrightMotor]= 0;
			motor[BrightMotor]= 0;
			motor[BleftMotor]= 0;
			motor[TleftMotor]= 0;
		}

	//Moving the speed must be less than or = 105
		void move(int speed, int val) {

			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);

			while(getMotorEncoder(rightMotor) <= val)
			  {
			    motor[rightMotor] = speed;
			    motor[leftMotor] = speed;
			}
		}

	//Turning left
		void turnLeft(int speed, int val){
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);

			motor[leftMotor]= speed *-1;
			motor[rightMotor]= speed;

			waitUntil(getMotorEncoder(leftMotor) <= val);

			motor[leftMotor]= 0;
			motor[rightMotor]= 0;
		}

		//Turning right
		void turnRight(int speed, int val){
			resetMotorEncoder(leftMotor);
			resetMotorEncoder(rightMotor);

			motor[leftMotor]= speed;
			motor[rightMotor]= speed * -1;

			waitUntil(getMotorEncoder(rightMotor) <= val);

			motor[leftMotor]= 0;
			motor[rightMotor]= 0;
		}




task main()
{

	////////////////////////////////////////////////////////
	//                 First Motion	  										//
	////////////////////////////////////////////////////////

	//Drop the hand down
	move(90);
	wait1Msec(700);
	move(-127);
	wait1Msec(500);

	//Move Stright to the cube
	move(127); // at the maximume speed
	wait1Msec(2000); // for 2 seconds

	grabing(127); // Starts to grab

	move(127); // go stright
	wait1Msec(2000); // for 2 seconds

	lifting(127); // Move the arm up
	droping(127); // release it

	turnLeft(100); // turn left
	wait1Msec(500); // for 300 micosecond
	move(127); // Move forward at a maximume speed
	wait1Msec(5000); // for 5 second

	turnLeft(100); // Turn left back at a speed of 100
	move(127); // Turn left back at a miximume speed
	wait1Msec(500); // for 500 microsecond




}
