#pragma config(Sensor, dgtl11, leftEncoder,    sensorRotation)
#pragma config(Sensor, dgtl12, rightEncoder,   sensorRotation)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main ()
{
// function to run autoDrive for set distance
void autoDrive(int speed, int distance)
{
	SensorValue(leftEncoder)= 0; 						//set optical shaft encoder to 0
	int ticks = 20/(4*PI) * 360; 					// convert the distance to optical shaft encoder value
	// 20 above is the distance that we want to go for (20 = just an example)
	while (abs(SensorValue(leftEncoder)) < ticks) 				// while left encoder less than the number of ticks																				// find the abs in Help > General C Programming > Math
{
	autoDrive(127, 20);				// input speed value // run the auto drive at set speed
}
	autoDrive (0, 0);												// stop the running motor
}
}
