#pragma config(Sensor, in1,    potentiometerScissorsLeft, sensorPotentiometer)
#pragma config(Sensor, in2,    potentiometerScissorsRight, sensorPotentiometer)
#pragma config(Sensor, in3,    potentiometerAngle, sensorPotentiometer)
#pragma config(Sensor, dgtl11, shaftEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           scissorsRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           scissorsLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mobileGoalLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           anglePivot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int setPoint = 1000;
int threshold = 15; // torelance between each joystick
int slewGrab = 80;

// PI variable {
	float kP = 0.27;
	float kI = 0.012;

int iLeft, pLeft = 0;
int iRight, pRight = 0;

int outputLeft = 0;
int outputRight = 0;

int errLeft = 0;
int errRight = 0;

int currentLeft = 0;
int currentRight = 0;
// PI variable }

void pid();

task main()
{
	while(true){
		pid();

		//get input into axis
		int y = vexRT[Ch2];
		int x = vexRT[Ch1];
		int r = vexRT[Ch4];

		if(abs(y) > threshold)	y = vexRT[Ch2];
		else	y = 0;

		if(abs(x) > threshold)	x = vexRT[Ch1];
		else	x = 0;

		if(abs(r) > threshold)	r = vexRT[Ch4]/2;
		else	r = 0;

		//angle controll
		if(vexRT[Btn6U] == 1){
      motor[anglePivot] = -100;
    } else if(vexRT[Btn6D] == 1){
      motor[anglePivot] = 100;
    } else{
      motor[anglePivot] = -20;
    }

		// MobileGoal Lift Control
		if(vexRT[Btn6UXmtr2] == 1){
			motor[mobileGoalLift] = 100;
		} else if(vexRT[Btn6DXmtr2] == 1){
			motor[mobileGoalLift] = -100;
		} else{
			motor[mobileGoalLift] = 30;
		}
		// Y component, X component, Rotation
		motor[frontLeft] =   y + x + r;
		motor[frontRight] =  -y + x + r;
		motor[backRight] =  -y - x + r;
		motor[backLeft] =   y - x + r;

		//Grab controll
		if(vexRT[Btn5UXmtr2] == 1){
      motor[claw] = -slewGrab;
    } else if(vexRT[Btn5DXmtr2] == 1){
      motor[claw] = slewGrab;
    } else{
      motor[claw] = 0;
    }
	}
}

void pid(){
	setPoint = 800 + (vexRT[Ch3Xmtr2] * 600/127);
	int motorLimit = 100;

	int totalValueLeft = 0;
	int totalValueRight = 0;

	int averageLeft = 0;
	int averageRight = 0;

	for(int i = 0; i < 10; i++){
		totalValueLeft += SensorValue[potentiometerScissorsLeft];
		totalValueRight += SensorValue[potentiometerScissorsRight];
	}
	averageRight = totalValueRight/10;
	averageLeft = totalValueLeft/10;

	errRight = setPoint - averageRight;
	errLeft = setPoint - averageLeft;

	pRight = (kP + .005) * errRight;
	pLeft = kP * errLeft;

	iLeft = kI * (i + errLeft);
	iRight = (kI + .001) * (i + errRight);

	currentLeft = averageLeft;
	currentRight = averageRight;

	outputLeft = pLeft + iLeft;
	outputRight = pRight + iRight;

	if(outputRight > motorLimit)  outputRight = motorLimit;
	else if(outputRight < -motorLimit)  outputRight = -motorLimit;

	if(outputLeft > motorLimit)  outputLeft = motorLimit;
	else if(outputLeft < -motorLimit)  outputLeft = -motorLimit;

	motor[scissorsLeft] = outputLeft;
	motor[scissorsRight] = outputRight;
}
