#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in6,    rightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in7,    leftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  shaft,          sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  left,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  right,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port2,           Tright,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Bright,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightGrab,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftGrab,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           Bleft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Tleft,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//define variable for sensors value
int rightPotentio;
int leftPotentio;
int shaftVal;
//The booleans is the function when driving
bool isGrab;
bool isRelease;
bool isLift;
bool isDrop;

//function for lift the arm
void liftArm(int speed) {
	motor[Tright] = speed; 	//top right motor
	motor[Bright] = speed; 	//bottom right motor
	motor[Tleft] = speed;		//top left
	motor[Bleft] = speed; 	//bottom left motor
}

//control the grab motors by set the range of the potentiometer
//each grab motor has a potentiometer
//value of the range is 0-4095
//the lesser the range, the grab will rotate more to the front
//the more the range, the grab will rotate more to the back
//1800 range - both grab is straight
void grabAtRange(int range){
	rightPotentio = SensorValue[rightPotentiometer]; 	//set the right potentiomter to variable rightPotentio
	leftPotentio = SensorValue[leftPotentiometer]; 		//set the left potentiomter to variable leftPotentio


	//the closer the motor is to the range the slower the motor, which make the grab accurate
	if(rightPotentio > range){	//if right grab potentio is bigger than the given range it will rotate to the front
		motor[rightGrab] = abs(rightPotentio - range)/10; //the speed of the rightGrab is the (different between the potentiometer and the range) divide 10
		}else if (rightPotentio < range){ //if right grab potentio is smaller than the given range it will rotate to the back
		motor[rightGrab] = abs(rightPotentio - range)/-10;
	}

	//left motor and potentio motor is the same with the right motor
	if(leftPotentio > range){
		motor[leftGrab] = abs(leftPotentio - range)/10;
		}else if (leftPotentio < range){
		motor[leftGrab] = abs(leftPotentio - range)/-10;
	}
}

task main()
{
	//disable PID for the wheels
	setPIDforMotor(port1, false);
	setPIDforMotor(port10, false);

	//reset the shaft encoder - in the game the code will delete because we already reset in automous period
	SensorValue[shaft] = 0;

	//the driving booleans start with false
	isGrab = false;
	isRelease = false;
	isLift = false;
	isDrop = false;

	while(true){
		//set the variables to the sensor values
		rightPotentio = SensorValue[rightPotentiometer];
		leftPotentio = SensorValue[leftPotentiometer];
		shaftVal = SensorValue[shaft];

		//the right and the left motor is fully control by the y-axis joysticks
		motor[rightMotor] = vexRT[Ch2];
		motor[leftMotor] = vexRT[Ch3];

		//if Btn6U clicked the arm will lift at 80 speed
		if(vexRT[Btn6U] == 1) {
			isLift = false;
			isDrop = false;
			liftArm(80);
		}else if(vexRT[Btn6D] == 1) {//if Btn6D clicked the arm will lift at -10 speed
			isLift = false;
			isDrop = false;
			liftArm(-10);
		}

		if(vexRT[Btn5D] == 1){//if Btn5D is clicked the hand will grab at 80 speed
			isGrab = false; //grab will disable in case the grab function will running
			isRelease = false; //release will disable in case the release function will running
			motor[leftGrab] = 80;
			motor[rightGrab] = 80;
		}else if(vexRT[Btn5U] == 1){//if Btn5U is clicked the hand will release at 80 speed
			isGrab = false;
			isRelease = false;
			motor[leftGrab] = -80;
			motor[rightGrab] = -80;
		}else{ //if Both of Btn5U and Btn5D isn't click, both hand will align each other
			if(leftPotentio > rightPotentio){ //if lefthand release more than the right it will move until it reach the right
				grabAtRange(rightPotentio);
				}else if(rightPotentio > leftPotentio){ //if righthand release more than the left it will move until it reach the left
				grabAtRange(leftPotentio);
			}
		}

		//Functions
		//Lift
		if(vexRT[Btn8U] == 1){
			isLift = true;
			isDrop = false;
		}
		//Drop
		if(vexRT[Btn8D] == 1){
			isDrop = true;
			isLift = false;
		}
		//Grab
		if(vexRT[Btn8L] == 1){
			isGrab = true;
			isRelease = false;
		}
		//Release
		if(vexRT[Btn8R] == 1){
			isRelease = true;
			isGrab = false;
		}

		//Arm will if isLift is true and shaftValue smaller than 90
		if(isLift && shaftVal < 90 ){
			liftArm(80);
			}else {
			isLift = false;
		}
		//Arm will if isDrop is true and shaftValue bigger than 0
		if(isDrop && shaftVal > 1 ){
			liftArm(-10);
			}else {
			isDrop = false;
		}

		//if (both isLift and isDrop equal false) and any other arm buttons isn't click the arm will lift at 15 speed so it will stop
		if((!isLift && !isDrop) && (vexRT[Btn6D] == 0 && vexRT[Btn6U] == 0)){
			liftArm(15);
		}

		//Grab to 350 range
		if(isGrab){
			grabAtRange(350);
		}

		//Release to 1500
		if(isRelease){
			grabAtRange(1500);
		}

	}
}
