#pragma config(Sensor, in6,    rightPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in7,    leftPotentiometer, sensorPotentiometer)
#pragma config(Motor,  port6,           rightGrap,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftGrap,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int left;
int right;

void grapAtRange(int range){
	right = SensorValue[rightPotentiometer];
	left = SensorValue[leftPotentiometer];
	if(right > range){
		motor[rightGrap] = abs(right - range)/10;
		}else if (right < range){
		motor[rightGrap] = abs(right - range)/-10;
	}

	if(left > range){
		motor[leftGrap] = abs(left - range)/10;
		}else if (left < range){
		motor[leftGrap] = abs(left - range)/-10;
	}
}


task main()
{
	while(1==1){
		right = SensorValue[rightPotentiometer];
		left = SensorValue[leftPotentiometer];

		if(vexRT[Btn5D] == 1)
		{
			motor[leftGrap] = 100;
			motor[rightGrap] = 100;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[leftGrap] = -100;
			motor[rightGrap] = -100;
		}
		else
		{
			if(left > right)
			{
				grapAtRange(right);
			}
			else if(right > left)
			{
				grapAtRange(left);
			}
		}
	}
}




/*while(!(right < range + 70 && right > range - 70) || !(left < range + 70 && left > range - 70)){*/
