#pragma config(Sensor, in1,    potentiometerScissorsLeft, sensorPotentiometer)
#pragma config(Sensor, in2,    potentiometerScissorsRight, sensorPotentiometer)
#pragma config(Sensor, in3,    potentiometerAngle, sensorPotentiometer)
#pragma config(Sensor, dgtl11, shaftEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           scissorsRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           scissorsLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mobileGoalLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           anglePivot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int setpoint =  SensorValue[potentiometerAngle]; // 1600 //480
int speedLimit = 100;
int vector = 1;

float kP = 0.12;
float kI = 0.11;

int err = 0;
int currentpot = 0;

int valueP = 0;
int valueI = 0;

int output = 0;

task pidRun(){
	while(true){
		currentpot = SensorValue[potentiometerAngle];
		err =  -1 * (setpoint - currentpot);

		valueP = kP * err;
		valueI = kI * (valueI + err);

		output = valueP + valueI;

		if(output > speedLimit) output = speedLimit;
		else if(output < -speedLimit) output = -speedLimit;
		if(abs(output) > 0 && setpoint < 2000){
			vector = output / abs(output);
			output = output +   vector * 7;
		}
	}
}
task main()
{
	startTask(pidRun);
	while(true){
		if(vexRT[Btn7U] == 1){
			setpoint = 4020;
		}

		if(vexRT[Btn7D] == 1){
			setpoint = 480;
		}

		if(vexRT[Btn7L] == 1){
			setpoint = 1500;
		}

		motor[anglePivot] = output;
	}
}
