#pragma config(Sensor, in1,    potentiometerScissorsLeft, sensorPotentiometer)
#pragma config(Sensor, in2,    potentiometerScissorsRight, sensorPotentiometer)
#pragma config(Sensor, in3,    potentiometerAngle, sensorPotentiometer)
#pragma config(Sensor, dgtl11, shaftEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           scissorsRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           scissorsLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mobileGoalLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           anglePivot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int angle;
int hold = 0;
int targetAngle;
int toleranceAngle = 50;

task holdAngleBar(){
	hold = 1;
	while (hold == 1){
		if (angle > 3800){
			motor[anglePivot]  = (angle - 3800)/10;
		}else if (angle < 700){
			motor[anglePivot]  = (angle-700)/20;
		}else if (angle - 700 > toleranceAngle || 3800 - angle > toleranceAngle){
			motor[anglePivot] = -20;
		}
	}
}

task moveAngleBar()
{
	hold = 0;
	while(abs(targetAngle - angle) > toleranceAngle){
		motor[anglePivot] = (angle - targetAngle)/abs(angle - targetAngle)*120;
	}
	startTask(holdAngleBar);
}



void moveAngle(int d){
	targetAngle = d;
	startTask(moveAngleBar);
}

task main()
{
	while (1 == 1){
		// Angle Pivot
		angle = SensorValue(potentiometerAngle);

		if (vexRT[Btn7D]){
			moveAngle(600);
		}
		if (vexRT[Btn7U]){
			moveAngle(3550);
		}
		if (vexRT[Btn7L]){
			moveAngle(1560);
		}
		if (vexRT[Btn7R]){
			moveAngle(1560);
		}
	}
}
