#pragma config(Sensor, in1,    potentiometerScissorsLeft, sensorPotentiometer)
#pragma config(Sensor, in2,    potentiometerScissorsRight, sensorPotentiometer)
#pragma config(Sensor, in3,    potentiometerAngle, sensorPotentiometer)
#pragma config(Sensor, dgtl11, shaftEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           scissorsRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           scissorsLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mobileGoalLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           anglePivot,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 10; 		// torelance between each joystick

int partL = 0;
int partR = 0;

int conL = 0;
int conR = 0;

void variableRun();
void wheelsRun();
void motorLeft(int speed);
void motorRight(int speed);

task main()
{
	while(true){
		//Input settingup
		variableRun();

		// Y component, X component, Rotation (MASTER CONTROLLER)
		// BTN: Ch4, Ch2, Ch1
		wheelsRun();
	}
}

void variableRun(){
		//get input into axis
		conL = vexRT[Ch3];
		conR = vexRT[Ch2];

		partL = vexRT[Ch3Xmtr2];
		partR = vexRT[Ch2Xmtr2];

		//get input into axis from controller

		if(abs(conL) < threshold)	conL = 0;
		else if(conL > 100) conL = 100;
		else if(conL < -100) conL = -100;

		if(abs(conR) < threshold)	conR = 0;
		else if(conR > 100) conR = 100;
		else if(conR < -100) conR = -100;

		//if(abs(partL) < threshold)	partL = 0;
		//if(abs(partR) < threshold)	partR = 0;
		//else if()
}

void wheelsRun(){
		motorLeft(conL);
		motorRight(conR);
}

void motorRight(int speed){
		motor[frontRight] 	=  speed;
		motor[backRight]	=  speed;
}

void motorLeft(int speed){
		motor[frontLeft] 	=  speed;
		motor[backLeft]	=  speed;
}
