#pragma config(Sensor, in1,    potentiometerScissorsLeft, sensorPotentiometer)
#pragma config(Sensor, in2,    potentiometerScissorsRight, sensorNone)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mobileGoalLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           scissorsRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port1,           anglePivot,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          grab,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port9,           scissorsLeft,  tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 15; // torelance between each joystick
int limitRPM = 160; // For high torque motor the has a limit speed
int sisSpeed = 100; // For scissors speed


void sciEqual(){
	int maxSpeed = 117;
	int potThreshold = 50;
	int maxDiff = 150;

	int err = abs((SensorValue[potentiometerScissorsRight]+30) - SensorValue[potentiometerScissorsLeft]);
	if(err > maxDiff){
		if(SensorValue[potentiometerScissorsRight] > SensorValue[potentiometerScissorsLeft]){
			motor[scissorsLeft] = 127;
			motor[scissorsRight] = sisSpeed - 25;
		} else{
			motor[scissorsLeft] = sisSpeed - 25;
			motor[scissorsRight] = 127;
		}
	} else if(err > potThreshold){
		if(SensorValue[potentiometerScissorsRight] > SensorValue[potentiometerScissorsLeft]){
			motor[scissorsLeft] = sisSpeed;
			motor[scissorsRight] = 127;
		} else{
			motor[scissorsLeft] = 127;
			motor[scissorsRight] = sisSpeed;
		}
	} else{
		motor[scissorsLeft] = sisSpeed;
		motor[scissorsRight] = sisSpeed;
	}
}

task main()
{
	while(true){
		//get input into axis
		int y = vexRT[Ch2];
		int x = vexRT[Ch1];
		int r = vexRT[Ch4];

		if(abs(y) > threshold && abs(y) < limitRPM)	y = vexRT[Ch2];
		else	y = 0;

		if(abs(x) > threshold && abs(x) < limitRPM)	x = vexRT[Ch1];
		else	x = 0;

		if(abs(r) > threshold)	r = vexRT[Ch4]/2;
		else	r = 0;

		// Y component, X component, Rotation
		motor[frontLeft] =   y + x + r;
		motor[frontRight] =  -y + x + r;
		motor[backRight] =  -y - x + r;
		motor[backLeft] =   y - x + r;

		// MobileGoal Lift Control
		if(vexRT[Btn6U] == 1){
			motor[mobileGoalLift] = 90;
			} else if(vexRT[Btn6D] == 1){
			motor[mobileGoalLift] = -90;
			} else{
			motor[mobileGoalLift] = 0;
		}

		int bias = 15;
		// Scissors Lift

		if(vexRT[Btn5U] == 1 || vexRT[Btn5UXmtr2] == 1){
			sisSpeed = sisSpeed;
			sciEqual();
		} else if(vexRT[Btn5D] == 1 || vexRT[Btn5DXmtr2] == 1){
			sisSpeed = -sisSpeed;
			sciEqual();
		} else{
			motor[scissorsLeft] = 20+bias;
			motor[scissorsRight] = 30;
		}

		// Grab Control
    if(vexRT[Btn7U] == 1 || vexRT[Btn7UXmtr2] == 1){
      motor[grab] = 127;
    } else if(vexRT[Btn7D] == 1 || vexRT[Btn7DXmtr2] == 1){
      motor[grab] = -127;
    } else{
      motor[grab] = 0;
    }

    motor[anglePivot] = vexRT[Ch2Xmtr2];
    motor[anglePivot] = vexRT[Ch2Xmtr2];

		// Motor values can only be updated every 20ms
		//wait10Msec(2);
	}
}
