#pragma config(Sensor, in1,    potentiometerScissorsLeft, sensorPotentiometer)
#pragma config(Sensor, in2,    potentiometerScissorsRight, sensorPotentiometer)
#pragma config(Sensor, in3,    potentiometerAngle, sensorPotentiometer)
#pragma config(Motor,  port1,           anglePivotLeft, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mobileGoalLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           scissorsLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           scissorsRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          anglePivotRight, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 15; // torelance between each joystick
int limitRPM = 160; // For high torque motor the has a limit speed
int sisSpeed = 100; // For scissors speed

int biasHigh = -25;
int biasLow = 25;

int left = 75;
int right = 120;

int leftPot = SensorValue[potentiometerScissorsLeft];
int rightPot = SensorValue[potentiometerScissorsRight];

void sciEqual(){
	int maxSpeed = 117;
	int potThreshold = 50;
	int maxDiff = 150;

	int err = abs((SensorValue[potentiometerScissorsRight]+20) - SensorValue[potentiometerScissorsLeft]);
	/*if(err > maxDiff){
		if(SensorValue[potentiometerScissorsRight] < SensorValue[potentiometerScissorsLeft]){
			motor[scissorsLeft] = sisSpeed + biasLow;			// the shorter with high speed
			motor[scissorsRight] = sisSpeed + biasHigh;		// the high with low speed
		} else{
			motor[scissorsLeft] = sisSpeed + biasHigh;		// the high with low speed
			motor[scissorsRight] = sisSpeed + biasLow;		// the shorter with high speed
		}
	} else */
	if(err > potThreshold){
		if(SensorValue[potentiometerScissorsRight] < SensorValue[potentiometerScissorsLeft]){
			motor[scissorsLeft] = sisSpeed + biasLow;							// the high normal speed
			motor[scissorsRight] = sisSpeed;	// the shorter speed up
		} else{
			motor[scissorsLeft] = sisSpeed + biasLow;
			motor[scissorsRight] = sisSpeed;
		}
	} else{
		motor[scissorsLeft] = sisSpeed;
		motor[scissorsRight] = sisSpeed;
	}
}

void go(){
	int speed = 100;

	int sp = 700;

}

task main()
{
	while(true){
		//get input into axis
		int y = vexRT[Ch2];
		int x = vexRT[Ch1];
		int r = vexRT[Ch4];

		if(abs(y) > threshold && abs(y) < limitRPM)	y = vexRT[Ch2];
		else	y = 0;

		if(abs(x) > threshold && abs(x) < limitRPM)	x = vexRT[Ch1];
		else	x = 0;

		if(abs(r) > threshold)	r = vexRT[Ch4]/2;
		else	r = 0;

		// Y component, X component, Rotation
		motor[frontLeft] =   y + x + r;
		motor[frontRight] =  -y + x + r;
		motor[backRight] =  -y - x + r;
		motor[backLeft] =   y - x + r;

		// MobileGoal Lift Control
		if(vexRT[Btn6U] == 1){
			motor[mobileGoalLift] = 90;
			} else if(vexRT[Btn6D] == 1){
			motor[mobileGoalLift] = -90;
			} else{
			motor[mobileGoalLift] = 0;
		}

		// Scissors Lift
		if((vexRT[Btn5U] == 1 || vexRT[Btn5UXmtr2] == 1) && leftPot>1000 && rightPot>1000){
			motor[scissorsLeft] = left;
			motor[scissorsRight] = right;
			} else if((vexRT[Btn5D] == 1 || vexRT[Btn5DXmtr2] == 1)&&leftPot<1380&&rightPot<1380){
			motor[scissorsLeft] = -40;
			motor[scissorsRight] = -40;
			} else{
			motor[scissorsRight] = 25+(rightPot - leftPot+70)/2;
			motor[scissorsLeft] = 25;
		}

		/*if(vexRT[Btn5U] == 1 || vexRT[Btn5UXmtr2] == 1){ //go up
			sisSpeed = sisSpeed;

			biasHigh = biasHigh;
			biasLow = biasLow;

			sciEqual();
		} else if(vexRT[Btn5D] == 1 || vexRT[Btn5DXmtr2] == 1){
			sisSpeed = -sisSpeed;

			biasHigh = -biasHigh;
			biasLow = -biasLow;

			sciEqual();
		} else{
			motor[scissorsLeft] = 20+bias;
			motor[scissorsRight] = 30;
		}*/

		// Grab Control

    if(vexRT[Btn7U] == 1 || vexRT[Btn7UXmtr2] == 1){
      motor[grab] = 50;
    } else if(vexRT[Btn7D] == 1 || vexRT[Btn7DXmtr2] == 1){
      motor[grab] = -70;
    } else{
      motor[grab] = 30;
    }

    // Angle Control
    if((vexRT[Btn8U] == 1 || vexRT[Btn8UXmtr2] == 1) && SensorValue[potentiometerAngle] < 2700){
      motor[anglePivotLeft] = 90;
      motor[anglePivotRight] = 90;
    } else if((vexRT[Btn8D] == 1 || vexRT[Btn8DXmtr2] == 1) && SensorValue[potentiometerAngle] > 100){
      motor[anglePivotLeft] = -60;
      motor[anglePivotRight] = -60;
    } else{
      motor[anglePivotLeft] = 20;
      motor[anglePivotRight] = 20;
    }

		// Motor values can only be updated every 20ms
		//wait10Msec(2);
	}
}
