#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Motor,  port2,           motorA,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static float  pid_Kp = 0.05; // 0.04
static float  pid_Ki = 0;
static float  pid_Kd = 0.5;	// 0.3

int currentValue = 0;
int err = 0;

float pidDrive = 0;
int expectedValue = 2500;

float dt = 10;
int err_prior = 0;

int pid_p = 0;
int pid_i = 0;
int pid_d = 0;

float pid_de = 0;
float pid_in = 0;

int output = 0;
bool onPID = true;
task main()
{

	while(onPID){
		currentValue = SensorValue[pot];
		err = expectedValue - currentValue;		// err = expected value - current value

		pid_de = err - err_prior;							// change in err
		if(10 > pid_de && pid_de > -10){				// set tolerance from -5 to 5
			pid_de = 0;
		}
		err_prior = err;											// past err = current err
		pid_in += err;												// sum of err

		pid_p = pid_Kp * err;									// Pgain * err
		pid_i = pid_Ki * pid_in;							// Igain * sum of err
		pid_d = pid_Kd * (pid_de/dt); 				// Dgain * change in err/ change of time

		output = pid_p + pid_i + pid_d;
		pidDrive = output;

		if( pidDrive > 127 )
			pidDrive = 127;
		if( pidDrive < (-127))
			pidDrive = (-127);

		motor[ motorA ] = pidDrive;
		wait1Msec(dt);
	}

}
