#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Motor,  port2,           motorA,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

static float  pid_Kp = 0.05;
static float  pid_Ki = 0.6;
static float  pid_Kd = 0.1;

int current = 0;
int err = 0;
int err_prior = 0;

float pidDrive = 0;
int expectedValue = 2500;

float pidDer = 0;

float d = 0;
float p = 0;


int iter = 25;
int bias = 20;
int inter = 0;

task main()
{
	while(true){
		current = SensorValue[pot];

		err = expectedValue - current;
		err_prior = err;

		pidDer = err - err_prior;

		//inter += err - iter;
		p = pid_Kp * err;
		d = (pid_Kd * pidDer);
		pidDrive = p + d; // + (pid_ki * inter)+ (pid_Kd * der) + bias

		if( pidDrive > 127 )
        pidDrive = 127;
    if( pidDrive < (-127) )
        pidDrive = (-127);

     motor[ motorA ] = pidDrive;

     wait1Msec(iter);
	}
}
