#pragma config(Sensor, in1,    potentiometerScissorsLeft, sensorPotentiometer)
#pragma config(Sensor, in2,    potentiometerScissorsRight, sensorPotentiometer)
#pragma config(Sensor, in3,    potentiometerAngle, sensorPotentiometer)
#pragma config(Sensor, dgtl11, shaftEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           scissorsLeft,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           scissorsRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mobileGoalLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           anglePivotRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * 1 represents the left motor and left potentiometer
 * 2 represents the right motor and right potentiometer
 */

 	float Kp = 0.25;
	float Ki = 0.01;

int encoder = 0;

int totVal1, totVal2 = 0;
int average1, average2 = 0;

int err1, output1 = 0;
int err2, output2 = 0;

int currentPos1 = 0;		// To display the
int currentPos2 = 0;

int sp = 500;			// Set Point
int p1,i1 = 0;
int p2,i2 = 0;

void pid(){
	int motorLimit = 80;
  for(int i = 0; i < 10; i++){
    totVal1 += SensorValue[potentiometerScissorsLeft]; // left potentiometer
    totVal2 += SensorValue[potentiometerScissorsRight]; // right potentiometer
  }

  average1 = totVal1/10;
  average2 = totVal2/10;

  err1 = -1 * (sp - average1); // -1 because when go up the value is smaller
	err2 = -1 * (sp - average2);

  p1 = Kp * err1;
  p2 = Kp * err2;

  i1 = Ki * (i1 + err1);
  i2 = Ki * (i2 + err2);

  currentPos1 = average1; // just to display
  currentPos2 = average2; // just to display

  output1 =  p1 + i1;
  output2 =  p2 + i2;

  if(output1 > motorLimit)  output1 = motorLimit;
  else if(output1 < -motorLimit)  output1 = -motorLimit;

  if(output2 > motorLimit)  output2 = motorLimit;
  else if(output2 < -motorLimit)  output2 = -motorLimit;

  totVal1 = 0; totVal2 = 0;
  average1 = 0; average2 = 0;
}

task main(){
	SensorValue[shaftEncoder] = 0;

  while(true){
  	encoder = SensorValue[shaftEncoder];
    pid();
    motor[scissorsRight] = output2 + 26;
    motor[scissorsLeft] = output1 + 18;

    //sp = (vexRT[Ch2] * (950/127)); // range joy stick to rang of the potentio of the scissor lift 0-127 to 2800-1200

    // MobileGoal Lift Control
		if(vexRT[Btn6U] == 1 && encoder > 30){
				motor[mobileGoalLift] = -127;
		} else if(vexRT[Btn6D] == 1){
				motor[mobileGoalLift] = 100;
		} else{
				motor[mobileGoalLift] = 0;
		}
  }
}
