#pragma config(Sensor, in1,    left,           sensorPotentiometer)
#pragma config(Sensor, in2,    right,          sensorPotentiometer)
#pragma config(Sensor, in3,    arm,            sensorPotentiometer)
#pragma config(Sensor, dgtl11, quad,           sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int potLeft = 0;
int potRight = 0;
int diff = 0;
int potArm = 0;

int priority = kHighPriority;

task potter(){
	nSchedulePriority = kHighPriority;
	while(true){
		potLeft = SensorValue[ left ];
	}
}
task main()
{
	nSchedulePriority = kHighPriority;
	startTask(potter, priority);
	while(true){
		potRight = SensorValue[ right ];
		potArm = SensorValue[arm];
		diff = abs(potRight - potLeft);
	}
}
