#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           TrightMotor,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BrightMotor,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           grabMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BleftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           TleftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{
	while(1 == 1){


		//Wheels remote control
		motor [rightMotor] = Ch2; //channel 3 controlling left motor
		motor [leftMotor] = Ch2; //channel 2 controlling right motor

		motor[leftMotor] = Ch1;
		motor[rightMotor] = Ch1;
		//End
	}


}
