#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           TrightMotor,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BrightMotor,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           grabMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BleftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           TleftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 1;

task main()
{
	while(1 == 1){
		//Setting the speed
		if(vexRT(Btn8U) == 1){
			int speed = 1;
		}else if(vexRT(Btn8D) == 1){
			int speed = 2;
		}else {
			int speed = 1;
		}
		//End

		//Wheels remote control
		motor [rightMotor] = Ch2 / speed; //channel 3 controlling left motor
		motor [leftMotor] = Ch2 / speed; //channel 2 controlling right motor

		motor[leftMotor] = Ch1 / speed;
		motor[rightMotor] = Ch1*-1 / speed;
		//End

		motor[TrightMotor] = vexRT(Ch3);
		motor[BrightMotor] = vexRT(Ch3);
		motor[TleftMotor] = vexRT(Ch3);
		motor[BleftMotor] = vexRT(Ch3);
		motor[grabMotor] = vexRT(Ch4);


	}


}
