#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           TrightMotor,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BrightMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           grabMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           BleftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           TleftMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1 == 1){
		if(vexRT(Btn8U) == 1){
			float Ch2 = vexRT(Ch2);
			float Ch1 = vexRT(Ch1);
		}else if(vexRT(Btn8D) == 1){
			float Ch2 = vexRT(Ch2)/2;
			float Ch1 = vexRT(Ch1)/2;
		}else {
			float Ch2 = vexRT(Ch2);
			float Ch1 = vexRT(Ch1);
		}
	}
}
