#pragma config(Sensor, in1,    PotentiometerArm, sensorPotentiometer)
#pragma config(Sensor, in2,    PotentiometerGrab, sensorPotentiometer)
#pragma config(Motor,  port1,           motorLeft,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           motorRight,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//programming joystick, all command must be placed in While Loop

//task main()
//{
//while (1=1)
//{
//motor[motorName] = vexRT[channel Number];

// if(vexRT[botton name] == 1)
//	{
//	motor [nameofMotor] = speed;
//	}
//	else if(vexRT[bottonName] == 1)
//	{
//		motor [nameofMotor] = speed;
//	}
//	else
//	{
//		motor [nameofMotor] = speed;
//	}
//}
//}

//JoyStickProgramming
task main()
{
	while (1==1)
	{
		motor [motorLeft] = vexRT[Ch3]; //channel 3 controlling left motor
		motor [motorRight] = vexRT[Ch2]; //channel 2 controlling right motor

		if (vexRT[Btn6U] == 1) // if botton 6U pressed
		{
		SensorValue[PotentiometerArm] =	127; // arm moves up
		}
		else if (vexRT[Btn6D] == 1) //when botton 6D being pressed
		{
		SensorValue[PotentiometerArm] = -127; // arm moves down
		}
		else
		{
		SensorValue[PotentiometerArm] = 0; //No botton pressed, don't do anything
		}
// New Botton clicking
		if (vexRT[Btn5U] == 1) // when botton 5U being pressed
		{
		SensorValue[PotentiometerGrab] = 127; //grab things in
		}
		else if (vexRT[Btn5D]  == 1) // when botton 5D being pressed
		{
		SensorValue[PotentiometerGrab] = -127; //grab released
		}
		else
		{
		SensorValue[PotentiometerGrab] = 0; // nothing pressed, don't do anything
		}
	}

}
